version: "3"
services:
  springboot-app:
    #container_name: spring-mysql-app
    image: springboot-app
    depends_on:
      - mysqldb
    build: . 
    ports:
      - "8080:8080"
#    environment:
#      MYSQL_HOST: mysqldb
#      MYSQL_USER: root
#      MYSQL_PASSWORD: root
#      MYSQL_PORT: 3306
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3307/test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC

      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root


      
   
  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: test
    
      MYSQL_ROOT_PASSWORD: root 